### ISSUE TITLE
I cloned this and tried to open it in VSCode on WSL2 but then it wanted to use Docker

### ISSUE THREAD

**Issue by nyck33** [scalingpythonml/scalingpythonml#19]
I clicked yes or okay and now I:m looking at a Jupyter page asking for a token.

![image](https://github.com/scalingpythonml/scalingpythonml/assets/25189545/efce6c89-46e9-46eb-bcba-5a489424bf90)

Where can I find this?

**Comment by nyck33** [comment]
I did `jupyter notebook list` from the VSCode terminal and was able to get the token but now see

![image](https://github.com/scalingpythonml/scalingpythonml/assets/25189545/c4fdaac2-0110-42c9-bbb8-bd7bcbb442a0)

What is this for?

**Comment by mlkimmins** [comment]
Hello~

this repo is for code examples in our forthcoming book! 

https://www.oreilly.com/library/view/scaling-python-with/9781098119867/

The notebook you are trying to deploy won't really work out of the box unless you deploy your own cluster and run jh labs.
